---
title: "Testing"
author: "José A. Bartolomei-Díaz, PhD - Outcome Project, LLC."
date: "April 4, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## UNE Weather Tests


```{r libraies}
library(ggplot2)
```

```{r load_data}
rm(list = ls(all = TRUE))
gc()
load("./data/weather.Rdata")
```

## Including Plots

Plot

```{r Plot_test, echo=FALSE}
ggplot(data = weather, aes(x = Date2, y = Temp_Out)) +
	geom_line(alpha = 0.5) +
	geom_smooth(na.rm = TRUE, colour = "green", fill = "pink")
	
```


```{r}
# to obtain the mean outside temperature by day, month and year
dmy <- aggregate(Temp_Out ~ dmy , data = weather,
								 FUN = function (x) mean(x, na.rm = TRUE))
str(dmy)

dmy$dmy2 <- as.Date(dmy$dmy, format = "%d/%m/%Y")
```

```{r}
# to obtain the mean outside temperature by month and year
aggregate(Temp_Out ~ my , data = weather, FUN = function (x) mean(x, na.rm = TRUE))

```

```{r Plot_test, echo=FALSE}
ggplot(data = weather, aes(x = dmy, y = Temp_Out)) +
	stat_summary(fun.y = "mean", geom = "line", na.rm = TRUE) +
	geom_smooth(na.rm = TRUE, colour = "green", fill = "pink") 
	

ggplot(data = weather, aes(x = dmy, y = Temp_Out)) +
	stat_summary(fun.data = "mean_cl_boot", geom = "line", na.rm = TRUE) +
	geom_smooth(na.rm = TRUE, colour = "green", fill = "pink") 
	
```
